### ISSUE TITLE
INFO  Application - 401 Unauthorized: GET - /api/user

### ISSUE THREAD

**Issue by pawan-jenu** [dragneelfps/realworld-kotlin-ktor#2]
why am i gettting this error

**Comment by pawan-jenu** [comment]
what do i need to pass, while accessing athenticated things

**Comment by dragneelfps** [comment]
@pawan-jenu you need to add header to the authencated requests, otherwise you will get the 401 errror.
```
Authorization: Token {{token}}
```
You can get the `token` from the response or login/register APIs.
